config/routes.rb
Cschools::Application.routes.draw do

  root :to => "home#index"

  resource :accounts do
    collection do
      post :login
      get :logout
    end
  end

  resources :users do
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  attr_accessible :name, :permalink
  has_many :users
end

app/controllers/account_controller.rb
class AccountController < ApplicationController

  def login

  end

  def logout

  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  layout 'account'

  def index
    init_current_user
  end

  def show
    init_current_user
  end

  def login
    user = User.find_by_username(params[:form][:username])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def new
    render :layout => 'home'
  end

  def create
    user_type = UserType.find_by_permalink("free")
    user = user_type.users.new(params[:form])
    user.save!
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def init_current_user
    @user = User.find_by_id(session[:user_id])
  end

  def user_is_logged_in?
    !session[:user_id].nil?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'home'

  def index
    if user_is_logged_in?
      init_current_user
      render :layout => 'account'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/destroy.html.erb
<h1>Accounts#destroy</h1>
<p>Find me in app/views/accounts/destroy.html.erb</p>

app/views/accounts/login.html.erb
<h1>Accounts#login</h1>
<p>Find me in app/views/accounts/login.html.erb</p>

app/views/accounts/logout.html.erb
<h1>Accounts#logout</h1>
<p>Find me in app/views/accounts/logout.html.erb</p>

app/views/accounts/new.html.erb
<div class="content-left">  
  <div class="row1">    
    <h1 class="title">Welcome To <span>XXXXX</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <%= form_for "user_form", :url => accounts_path, :html => {:method => :post} do %>
      <div id="bluebox" class="nice" style="margin-left: 80px;margin-top: 63px;margin-bottom:16px;">
	<div class="corner"></div><div class="tag"></div>
	<div class="text-with-tag"><strong>Fill out the information below to submit your property to our network of investors and their buyers</strong></div>
	
	<div class="form-row">
	  <label for="address">First Name: <span style="color:red"> *</span></label>
	  <input class="nice-field" name="form[first_name]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="sqft">Last Name: <span style="color:red"> *</span></label>
	  <input class="nice-field" name="form[last_name]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="monthly">Username: <span style="color:red"> *</span></label>
	  <input class="nice-field" name="form[username]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="phone">Password: <span style="color:red"> *</span></label>
	  <input class="nice-field" name="form[password]" size="30" type="password">
	</div>
	
	<div class="form-row">
	  <label for="phone2">Contact Number: <span style="color:red"> *</span></label>
	  <input class="nice-field" name="form[mobile_number]" size="30" type="password">
	</div>
	
	<div class="form-row">
	  <input type="checkbox" name="marketing_release"> <span style="padding-right: 10px;"><strong>By checking this box, I give you permission to submit my house to your buyers network to see how many offers I receive.  I understand I am Not obligated to sell my house under this program.</strong></span>
	</div>
	<div style="clear:both;"></div>
	<input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>            
    <% end %>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>
    <p>It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was
      popularised in the 1960s with the release </p>
    <ul class="list1">
      <li>of Letraset sheets containing</li>
      <li>Lorem Ipsum passages,</li>
      <li>and more recently with desktop</li>
    </ul>
    <p>&nbsp;<br>
      <strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it.<br>
      <br>
    </p>
  </div>
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it to make a type specimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="mainmenu">
    <h2 class="sidebar1">Join XXXXX</h2>
    <div class="text_box">
      <div class="login-title">Customer login</div>
      <%= form_for "user_login", :url => login_accounts_path, :html => {:method => :post} do %>
      <div class="login_form_row">
        <label class="login_label">Username:</label><input type="text" name="form[username]" class="login_input">
      </div>      
      <div class="login_form_row">
        <label class="login_label">Password:</label><input type="password" name="form[password]" class="login_input">
      </div>                                     
      <input type="image" src="/images/login.gif" class="login">
      <% end %>
    </div>
  </div>
  <div class="contact">
    <h2 class="sidebar2">News Feed</h2>
    <div class="content_right_section">            	
      <div class="header_02">What customers are saying..</div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">George Glumac</div>
          <p>I have checked out at least a dozen real estate investing systems in the past 16 months and spent a ton of money looking for integrity... 
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Rose Robinson</div>
          <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team!
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_07.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Joe Riddell</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/home/_index.html.erb
<div class="content-left">
  <div class="row1">
    <h1 class="title">Welcome To <span>XXXXX</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>
    <p>It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was
      popularised in the 1960s with the release </p>
    <ul class="list1">
      <li>of Letraset sheets containing</li>
      <li>Lorem Ipsum passages,</li>
      <li>and more recently with desktop</li>
    </ul>
    <p>&nbsp;<br>
      <strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it.<br>
      <br>
    </p>
  </div>  
  <div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
    <hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"/></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Great beginning, I am very pleased with what I have seen about this program so far. I look forward to learning more, and generating a good income. <br><a class="more-news-a">2 minutes ago</a></p>
      </div>
    </div>  
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">5 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">10 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">George Glumac</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">15 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">20 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">21 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
</div>
</div>

<div class="content-right">
  <div class="mainmenu">
    <h2 class="sidebar1">Join XXXXX</h2>
    <div class="text_box">
      <div class="login-title">Customer login</div>
      <%= form_for "user_login", :url => login_accounts_path, :html => {:method => :post} do %>
      <div class="login_form_row">
        <label class="login_label">Username:</label><input type="text" name="form[username]" class="login_input">
      </div>      
      <div class="login_form_row">
        <label class="login_label">Password:</label><input type="password" name="form[password]" class="login_input">
      </div>                                     
      <input type="image" src="/images/login.gif" class="login">
      <% end %>
    </div>
    <div class="signup-note">Don't have an account yet! &nbsp;&nbsp;<a href="<%= new_accounts_path%>">Signup</a></div>
  </div>
  <div class="contact">
    <h2 class="sidebar2">News Feed</h2>
    <div class="content_right_section">            
      <div class="header_02">What customers are saying..</div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">George Glumac</div>
          <p>I have checked out at least a dozen real estate investing systems in the past 16 months and spent a ton of money looking for integrity... 
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Rose Robinson</div>
          <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team!
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_07.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Joe Riddell</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
    </div>    
  </div>
</div>

app/views/home/index.html.erb
<% unless @user.nil?  %>
<%= render :partial => "dashboard" %>
<% else %>
<%= render :partial => "index" %>
<% end %>

app/views/layouts/account.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>New Site</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <%= stylesheet_link_tag    "home" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="page-out">
      <div class="page-in">
	<div class="page">
	  <div class="main">
	    <div class="header">
	      <div class="header-top">
		<h1>New <span>Site</span></h1>
	      </div>
	      <div class="header-bottom">
		<h2>Lorem Ipsum is simply dummy text<br>
		  of the typesetting industry.</h2>
	      </div>
	      <div class="topmenu">
		<ul>
		  <li
		     style="background: transparent none repeat scroll 0% 50%; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; padding-left: 0px;"><a href="#" class="active"><span>Home</span></a></li>
		  <li><a href="#"><span>My XXXXX</span></a></li>
		  <li><a href="#"><span>Requests</span></a></li>
		  <li><a href="#"><span>Services</span></a></li>
		  <li><a href="#"><span>Contact</span></a></li>
		  <li><a href="#"><span>Resources</span></a></li>
		  <li><a href="#"><span>Links</span></a></li>
		</ul>
	      </div>
	    </div>
	    <div class="content">
	      <%= yield %>            
	    </div>
	    <div class="footer">
	      <p>&copy; Copyright 2013. Powered by <a target="_blank" href="javascript:;">XXXXX</a><br>
	      </p>
	      <ul>
		<li style="border-left: medium none;"><a href="index.html"><span>Home</span></a></li>
		<li><a href="#"><span>About&nbsp;us</span></a></li>
		<li><a href="#"><span>What's&nbsp;new</span></a></li>
		<li><a href="#"><span>Services</span></a></li>
		<li><a href="#"><span>Contact</span></a></li>
		<li><a href="#"><span>Resources</span></a></li>
		<li style="padding-right: 0px;"><a href="#"><span>Links</span></a></li>
	      </ul>
	    </div>
	  </div>
	</div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cschools</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>New Site</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />  
    <%= stylesheet_link_tag "home" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="page-out">
      <div class="page-in">
	<div class="page">
	  <div class="main">
	    <div class="header">
	      <div class="header-top">
		<h1>New <span>Site</span></h1>
	      </div>
	      <div class="header-bottom">
		<h2>Are you tired of wandering across the streets<br>
		  searching for a xxxxx..?<br>
		  Now we help you find your wish xxxxx<br>
		  in your wish place with single click!!</h2>
	      </div>
	      <div class="topmenu">
		<ul>
		  <li
		     style="background: transparent none repeat scroll 0% 50%; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; padding-left: 0px;">
		    <a href="/" class="<%= 'active' if params[:action] == 'index' %>"><span>Home</span></a>
		  </li>
		  <li><a href="#"><span>About us</span></a></li>
		  <li><a href="#"><span>Services</span></a></li>
		  <li><a href="#"><span>Contact</span></a></li>
		  <li><a href="#"><span>Pricing</span></a></li>
		  <li><a href="#"><span>Find my xxxxx</span></a></li>
		</ul>
	      </div>
	    </div>
	    <div class="content">
	      <%= yield %>            
	    </div>
	    <div class="footer">
	      <p>&copy; Copyright 2012. New Site Private Ltd.</a><br></p>
              <ul>
		<li style="border-left: medium none;"><a href="index.html"><span>Home</span></a></li>
		<li><a href="#"><span>About&nbsp;us</span></a></li>
		<li><a href="#"><span>What's&nbsp;new</span></a></li>
		<li><a href="#"><span>Services</span></a></li>
		<li><a href="#"><span>Contact</span></a></li>
		<li><a href="#"><span>Resources</span></a></li>
		<li style="padding-right: 0px;"><a href="#"><span>Links</span></a></li>
	      </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>